name: "ginblog-be"
mode: "dev"
port: 3000
version: "v0.0.1"
start_time: "2023-12-29"
machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "debug"
  filename: "./log/ginblog.log"
  max_size: 1000
  max_age: 3600
  max_backups: 5

mysql:
  driver: "mysql"
  host: "192.168.194.35"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "ginblog"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "192.168.194.35"
  port: 6379
  password: ""
  db: 0
  pool_size: 100

minio:
  endpoint: "192.168.194.35:9000"
  access_key: minioadmin
  secret_key: minioadmin
  bucketname: test
  usessl: false
